### ISSUE TITLE
[Enhancement] Add a list of recently copied colors

### ISSUE THREAD

**Issue by Leo-Peyronnet** [Leo-Corporation/ColorPicker#16]
**Enhancement:**
Add a list of recently copied colors.

**Describe the solution:**
Add a list with recent copied colors:

- [x] When clicking on one of the colors, it copies the RGB color
- [x] When hovering a color, a tooltip displays RGB and HEX colors
- [x] A button to clear the list
