### ISSUE TITLE
[Enhancement] Add the Selector page

### ISSUE THREAD

**Issue by Leo-Peyronnet** [Leo-Corporation/ColorPicker#194]
### Enhancement

- [x] #195
- [x] #196
- [x] #197
- [x] #198
    - [x] RGB Values are visible next to the sidebar and also in the panel
    - [x] HEX, HSL, HSV, CMYK, XYZ, YIQ, YUV* are also visible in this panel
    - [x] Hovering the values should show a little copy button alongside with a hover effect where the background color changes slightly
    - [x] Clicking on each value should copy them to the clipboard of the user.
- [x] #199
