### ISSUE TITLE
[Enhancement] Add the Bookmarks page

### ISSUE THREAD

**Issue by Leo-Peyronnet** [Leo-Corporation/ColorPicker#229]
### Enhancement

- [x] The user interface features the following categories:
    - [x] Colors (regular colors)
    - [x] Palette (a set of generated colors)
    - [x] Gradient (the gradient with all its parameters)
- [x] #231
- [x] #230
