### ISSUE TITLE
[Enhancement] Add MainWindow

### ISSUE THREAD

**Issue by Leo-Peyronnet** [Leo-Corporation/ColorPicker#241]
### Enhancement

- [x] The background is a mesh gradient with subtle colors.
- [x] The window is resizable and responsive.
- [x] Basic window behavior (maximize, restore, minimize, close)
- [x] Possibility to pin the window (always on top)
- [x] A side bar is present on the left side:
    - [x] Main features are inside of colorful squares (Home, Bookmarks and settings)
    - [x] A second category for other features is under the first one
    - [x] Each feature is grouped by category; the user can expand a category when clicking on the category button.
    - [x] All of the icons are animated.
